# Path to sources
# sonar.sources=
# sonar.exclusions=packages/api/**/*,**/test.ts*
sonar.inclusions=packages/ui-client-common/src/**/*.ts,packages/ui-client-common/src/**/*.tsx

# Path to tests
# sonar.tests=packages
# sonar.test.exclusions=
sonar.test.inclusions=packages/ui-client-common/src/**/*.test.ts,packages/ui-client-common/src/**/*.test.tsx

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
# sonar.cpd.exclusions=
