packages:
  - packages/*

overrides:
  '@openapitools/openapi-generator-cli>axios': 1.16.0

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@swc/core'
  - esbuild
  - nx
  - playwright
  - unrs-resolver
