packages:
  - packages/*
  - examples/*

overrides:
  '@openapitools/openapi-generator-cli>axios': 1.16.0

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@swc/core'
  - esbuild
  - nx
  - playwright
  - unrs-resolver

allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  nx: true
  unrs-resolver: true

lockfile: true
