/// <reference types="vitest" />

import {
  globSync,
  writeFileSync,
} from 'fs';
import { join } from 'path';

import { playwright } from '@vitest/browser-playwright';
import react from '@vitejs/plugin-react-swc';
import svgr from 'vite-plugin-svgr';
import dts from 'vite-plugin-dts';
import { libInjectCss } from 'vite-plugin-lib-inject-css';
import { defineConfig } from 'vitest/config';
import { esmExternalRequirePlugin } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';

const createIndex = () => {
  const indexFilePath = join(__dirname, 'src', 'index.ts');
  let indexContent = `// This file is auto-generated by Vite. Do not edit manually.\n\n`;
  globSync([
    join(__dirname, 'src', '**/index.ts'),
    join(__dirname, 'src', 'data', '*.ts'),
    join(__dirname, 'src', 'models', '*.ts'),
  ]).forEach((file) => {
    const relativePath = file.replace(`${__dirname}/src/`, '');
    if (relativePath === 'index.ts') {
      return;
    }
    indexContent += `export * from './${relativePath.replace(/\/index\.ts$/, '')}';\n`;
  });
  writeFileSync(indexFilePath, indexContent, 'utf8');
  return './src/index.ts';
};

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({ tsDecorators: true }),
    svgr(),
    libInjectCss(),
    dts({
      insertTypesEntry: true,
      rollupTypes: true,
      tsconfigPath: './tsconfig.json',
    }),
    viteStaticCopy({
      targets: [
        {
          src: [
            './src/@types/**/*.d.ts',
          ],
          dest: './',
          rename: { stripBase: true },
          transform: (content) => content.replace(/from '\.\.\/classes\/[^']+'/g, "from './index'"),
        },
        {
          src: [
            './src/locale',
          ],
          dest: './locale',
          rename: { stripBase: true },
        },
      ],
    }),
  ],
  build: {
    rolldownOptions: {
      external: (id) => [
        '@emotion/cache',
        '@emotion/react',
        '@emotion/styled',
        '@mui/icons-material',
        '@mui/material',
        '@mui/styled-engine',
        '@mui/system',
        '@mui/utils',
        '@mui/x-date-pickers',
        'i18next',
        'react-dom',
        'react-i18next',
        'react',
      ].some((pkg) => id === pkg || id.startsWith(`${pkg}/`)),
      plugins: [esmExternalRequirePlugin()],
      treeshake: true,
    },
    copyPublicDir: false,
    lib: {
      fileName: () => {
        return 'index.js';
      },
      entry: createIndex(),
      formats: ['es'],
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      tsconfig: 'tsconfig.json',
    },
  },
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: './coverage',
      exclude: [
        'node_modules/',
        'dist/',
        '.next/',
        'build/',
        'src/api/**/*',
        '**/*.config.{js,ts}',
        '**/*.test.{js,ts,jsx,tsx}',
        '**/*.spec.{js,ts,jsx,tsx}',
        '**/test/**',
        '**/tests/**',
      ],
    },
    projects: [
      {
        test: {
          include: [
            'src/**/*.test.ts',
          ],
          name: 'unit',
          environment: 'jsdom',
          globals: true,
          setupFiles: ['./src/test/setup-jsdom.ts'],
          testTimeout: 5000,
        },
      },
      {
        plugins: [
          react({ tsDecorators: true }),
        ],
        test: {
          include: [
            'src/test/integration/**/*.test.{ts,tsx}',
          ],
          name: 'browser',
          setupFiles: ['./src/test/setup-browser.ts'],
          testTimeout: 30000,
          globals: true,
          browser: {
            enabled: true,
            headless: !!process.env.CI,
            provider: playwright(),
            // https://vitest.dev/config/browser/playwright
            instances: [
              { browser: 'chromium' },
            ],
          },
        },
      },
    ],
  },
});
