export enum ADMIN_PAGE_CATEGORY {
  ACCESS_RIGHTS = 'ACCESS_RIGHTS',
  HELPERS = 'HELPERS',
  REFERENCE_DATA = 'REFERENCE_DATA',
  SYSTEM = 'SYSTEM',
  USERS_AND_ORGANIZATIONS = 'USERS_AND_ORGANIZATIONS',
}
