/// <reference types="vitest" />

import {
  globSync,
  writeFileSync,
} from 'fs';
import { join } from 'path';

import react from '@vitejs/plugin-react';
import svgr from 'vite-plugin-svgr';
import dts from 'vite-plugin-dts';
import { libInjectCss } from 'vite-plugin-lib-inject-css';
import { defineConfig } from 'vitest/config';
import { viteStaticCopy } from 'vite-plugin-static-copy';
import { esmExternalRequirePlugin } from 'vite';
import { playwright } from '@vitest/browser-playwright';

export const createIndex = () => {
  const indexFilePath = join(__dirname, 'src', 'index.ts');
  let indexContent = `/* eslint-disable perfectionist/sort-exports */\n\n// This file is auto-generated by Vite. Do not edit manually.\n\n`;
  globSync([
    join(__dirname, 'src', '**/index.ts'),
    join(__dirname, 'src', 'data', '*.ts'),
    join(__dirname, 'src', 'models', '*.ts'),
  ]).forEach((file) => {
    const relativePath = file.replace(`${__dirname}/src/`, '');
    if (relativePath === 'index.ts') {
      return;
    }
    indexContent += `export * from './${relativePath.replace(/\/index\.ts$/, '')}';\n`;
  });
  writeFileSync(indexFilePath, indexContent, 'utf8');
  return './src/index.ts';
};

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    copyPublicDir: false,
    lib: {
      entry: createIndex(),
      fileName: () => {
        return 'index.js';
      },
      formats: ['es'],
    },
    rolldownOptions: {
      plugins: [
        esmExternalRequirePlugin({
          external: [
            /^@emotion\/cache(\/.+)?$/,
            /^@emotion\/react(\/.+)?$/,
            /^@emotion\/styled(\/.+)?$/,
            /^@gen-epix\/ui(\/.+)?$/,
            /^@mui\/icons-material(\/.+)?$/,
            /^@mui\/material(\/.+)?$/,
            /^@mui\/styled-engine(\/.+)?$/,
            /^@mui\/system(\/.+)?$/,
            /^@mui\/utils(\/.+)?$/,
            /^@mui\/x-date-pickers(\/.+)?$/,
            /^axios(\/.+)?$/,
            /^i18next(\/.+)?$/,
            /^react(-dom|-i18next|-router(-dom)?)?(\/.+)?$/,
          ],
        }),
      ],
      treeshake: true,
    },
    sourcemap: true,
  },
  plugins: [
    react(),
    svgr(),
    libInjectCss(),
    dts({
      beforeWriteFile: (filePath, content) => {
        if (/[/\\]dist[/\\]index\.d\.ts$/.test(filePath) && content.trim() === 'export {}') {
          return {
            content: "export * from './src/index'\nexport {}\n",
            filePath,
          };
        }

        return {
          content,
          filePath,
        };
      },
      bundleTypes: true,
      insertTypesEntry: true,
      tsconfigPath: './tsconfig.build.json',
    }),
    viteStaticCopy({
      targets: [
        {
          dest: './',
          rename: { stripBase: true },
          src: [
            './src/@types/**/*.d.ts',
          ],
        },
        {
          dest: './locale',
          rename: { stripBase: true },
          src: [
            './src/locale',
          ],
        },
      ],
    }),
  ],
  test: {
    coverage: {
      exclude: [
        'node_modules/',
        'dist/',
        '.next/',
        'build/',
        'src/api/**/*',
        '**/*.config.{js,ts}',
        '**/*.test.{js,ts,jsx,tsx}',
        '**/*.spec.{js,ts,jsx,tsx}',
        '**/test/**',
        '**/tests/**',
      ],
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: './coverage',
    },
    projects: [
      {
        plugins: [
          {
            configResolved: () => {
              createIndex();
            },
            name: 'on-config-resolved',
          },
        ],
        test: {
          environment: 'jsdom',
          globals: true,
          include: [
            'src/**/*.test.ts',
          ],
          name: 'unit',
          setupFiles: ['./src/test/setup/setup-jsdom.ts'],
          testTimeout: 5000,
        },
      },
      {
        plugins: [
          react(),
        ],
        test: {
          browser: {
            enabled: true,
            headless: !!process.env.CI,
            // https://vitest.dev/config/browser/playwright
            instances: [
              { browser: 'chromium' },
            ],
            provider: playwright(),
            viewport: {
              height: 1080,
              width: 1920,
            },
          },
          globals: true,
          include: [
            'src/**/*.test.tsx',
          ],
          name: 'browser',
          setupFiles: ['./src/test/setup/setup-browser.ts'],
          testTimeout: 30000,
        },
      },
    ],
  },
});
