name: "Setup Node Environment"
description: "Setup Node, cache and clean install"

inputs:
  node-version:
    description: "The Node.js version to use"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
