name: "Setup Node Environment"
description: "Setup Node, cache and clean install"

inputs:
  node-version:
    description: "The Node.js version to use"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{inputs.node-version}}
    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
