export const COMMON_QUERY_KEY = {
  CONTACTS: 'CONTACTS',
  FEATURE_FLAGS: 'FEATURE_FLAGS',
  IDENTIFIER_ISSUER_LINKS: 'IDENTIFIER_ISSUER_LINKS',
  IDENTIFIER_ISSUERS: 'IDENTIFIER_ISSUERS',
  IDENTIFIER_ISSUERS_OWN_ORGANIZATION: 'IDENTIFIER_ISSUERS_OWN_ORGANIZATION',
  IDENTITY_PROVIDERS: 'IDENTITY_PROVIDERS',
  INVITE_USER_CONSTRAINTS: 'INVITE_USER_CONSTRAINTS',
  LICENSES: 'LICENSES',
  ORGANIZATION_ADMIN_NAME_EMAILS: 'ORGANIZATION_ADMIN_NAME_EMAILS',
  ORGANIZATION_ADMIN_POLICIES: 'ORGANIZATION_ADMIN_POLICIES',
  ORGANIZATIONS: 'ORGANIZATIONS',
  OUTAGES: 'OUTAGES',
  SITES: 'SITES',
  USER_INVITATIONS: 'USER_INVITATIONS',
  USER_ME: 'USER_ME',
  USER_PERMISSIONS: 'USER_PERMISSIONS',
  USERS: 'USERS',
} as const;

// eslint-disable-next-line no-redeclare, @typescript-eslint/naming-convention
export type COMMON_QUERY_KEY = typeof COMMON_QUERY_KEY[keyof typeof COMMON_QUERY_KEY];

export const COMMON_QUERY_DEPENDENCIES: Record<COMMON_QUERY_KEY, COMMON_QUERY_KEY[]> = {
  [COMMON_QUERY_KEY.CONTACTS]: [
    COMMON_QUERY_KEY.SITES,
  ],
  [COMMON_QUERY_KEY.FEATURE_FLAGS]: [],
  [COMMON_QUERY_KEY.IDENTIFIER_ISSUER_LINKS]: [
    COMMON_QUERY_KEY.IDENTIFIER_ISSUERS,
  ],
  [COMMON_QUERY_KEY.IDENTIFIER_ISSUERS]: [],
  [COMMON_QUERY_KEY.IDENTIFIER_ISSUERS_OWN_ORGANIZATION]: [
    COMMON_QUERY_KEY.IDENTIFIER_ISSUER_LINKS,
    COMMON_QUERY_KEY.IDENTIFIER_ISSUERS,
    COMMON_QUERY_KEY.ORGANIZATIONS,
  ],
  [COMMON_QUERY_KEY.IDENTITY_PROVIDERS]: [],
  [COMMON_QUERY_KEY.INVITE_USER_CONSTRAINTS]: [
    COMMON_QUERY_KEY.ORGANIZATIONS,
  ],
  [COMMON_QUERY_KEY.LICENSES]: [],
  [COMMON_QUERY_KEY.ORGANIZATION_ADMIN_NAME_EMAILS]: [
    COMMON_QUERY_KEY.ORGANIZATION_ADMIN_POLICIES,
    COMMON_QUERY_KEY.ORGANIZATIONS,
  ],
  [COMMON_QUERY_KEY.ORGANIZATION_ADMIN_POLICIES]: [],
  [COMMON_QUERY_KEY.ORGANIZATIONS]: [],
  [COMMON_QUERY_KEY.OUTAGES]: [],
  [COMMON_QUERY_KEY.SITES]: [],
  [COMMON_QUERY_KEY.USER_INVITATIONS]: [],
  [COMMON_QUERY_KEY.USER_ME]: [],
  [COMMON_QUERY_KEY.USER_PERMISSIONS]: [
    COMMON_QUERY_KEY.USERS,
  ],
  [COMMON_QUERY_KEY.USERS]: [
    COMMON_QUERY_KEY.USER_INVITATIONS,
  ],
};
