export const DASHBOARD_COMPONENT_NAME = {
  EPI_CURVE: 'EPI_CURVE',
  HISTOGRAM: 'HISTOGRAM',
  LEGENDA: 'LEGENDA',
  LINE_LIST: 'LINE_LIST',
  MAP: 'MAP',
  SEARCH_BOX: 'SEARCH_BOX',
  TREE: 'TREE',
};
