/* eslint-disable */
/**
 * Generated by @gen-epix/generate-common-api.
 * Do not edit this file manually.
 */

import type { AxiosResponse, RawAxiosRequestConfig } from 'axios';

export interface CommonDbApiPermission {
  'command_name': CommonDbCommandName;
  'permission_type': CommonDbPermissionType;
}


export const CommonDbAuthProtocol = {
  NONE: 'NONE',
  OAUTH2: 'OAUTH2',
  OIDC: 'OIDC',
} as const;

export type CommonDbAuthProtocol = typeof CommonDbAuthProtocol[keyof typeof CommonDbAuthProtocol];


export const CommonDbCommandName = {
  SiteCrudCommand: 'SiteCrudCommand',
  DataCollectionSetMemberCrudCommand: 'DataCollectionSetMemberCrudCommand',
  DataCollectionSetCrudCommand: 'DataCollectionSetCrudCommand',
  DataCollectionSetDataCollectionUpdateAssociationCommand: 'DataCollectionSetDataCollectionUpdateAssociationCommand',
  GetIdentityProvidersCommand: 'GetIdentityProvidersCommand',
  RetrieveOutagesCommand: 'RetrieveOutagesCommand',
  OrganizationCrudCommand: 'OrganizationCrudCommand',
  ContactCrudCommand: 'ContactCrudCommand',
  OrganizationAdminPolicyCrudCommand: 'OrganizationAdminPolicyCrudCommand',
  OrganizationSetCrudCommand: 'OrganizationSetCrudCommand',
  OutageCrudCommand: 'OutageCrudCommand',
  RetrieveSubRolesCommand: 'RetrieveSubRolesCommand',
  OrganizationSetMemberCrudCommand: 'OrganizationSetMemberCrudCommand',
  OrganizationSetOrganizationUpdateAssociationCommand: 'OrganizationSetOrganizationUpdateAssociationCommand',
  RetrieveOrganizationContactsCommand: 'RetrieveOrganizationContactsCommand',
  RetrieveLicensesCommand: 'RetrieveLicensesCommand',
  UpdateUserOwnOrganizationCommand: 'UpdateUserOwnOrganizationCommand',
  UserCrudCommand: 'UserCrudCommand',
  UpdateUserCommand: 'UpdateUserCommand',
  InviteUserCommand: 'InviteUserCommand',
  OrganizationIdentifierIssuerLinkCrudCommand: 'OrganizationIdentifierIssuerLinkCrudCommand',
  UserInvitationCrudCommand: 'UserInvitationCrudCommand',
  RetrieveOrganizationsUnderAdminCommand: 'RetrieveOrganizationsUnderAdminCommand',
  RegisterInvitedUserCommand: 'RegisterInvitedUserCommand',
  RetrieveFeatureFlagsCommand: 'RetrieveFeatureFlagsCommand',
  RetrieveInviteUserConstraintsCommand: 'RetrieveInviteUserConstraintsCommand',
  RetrieveOwnPermissionsCommand: 'RetrieveOwnPermissionsCommand',
  IdentifierIssuerCrudCommand: 'IdentifierIssuerCrudCommand',
  OrganizationIdentifierIssuerLinkUpdateAssociationCommand: 'OrganizationIdentifierIssuerLinkUpdateAssociationCommand',
  RetrieveOrganizationAdminNameEmailsCommand: 'RetrieveOrganizationAdminNameEmailsCommand',
  DataCollectionCrudCommand: 'DataCollectionCrudCommand',
} as const;

export type CommonDbCommandName = typeof CommonDbCommandName[keyof typeof CommonDbCommandName];


export const CommonDbComparisonOperator = {
  Less_Than: '<',
  Less_Than_Or_Equal_To: '<=',
  Equal: '=',
  Greater_Than_Or_Equal_To: '>=',
  Greater_Than: '>',
  Not_Equal: '!=',
} as const;

export type CommonDbComparisonOperator = typeof CommonDbComparisonOperator[keyof typeof CommonDbComparisonOperator];


export interface CommonDbContact {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'site_id': string;
  'site'?: CommonDbSite;
  'name': string;
  'email'?: string | null;
  'phone'?: string | null;
}


export interface CommonDbDataCollection {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'name': string;
  'description'?: string | null;
}


export interface CommonDbDataCollectionSet {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'name': string;
  'description'?: string | null;
}


export interface CommonDbDataCollectionSetMember {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'data_collection_set_id': string;
  'data_collection_set'?: CommonDbDataCollectionSet;
  'data_collection_id': string;
  'data_collection'?: CommonDbDataCollection;
}


export const CommonDbDataIssueType = {
  MISSING: 'MISSING',
  INVALID: 'INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  CONFLICT: 'CONFLICT',
  DERIVED: 'DERIVED',
  TRANSFORMED: 'TRANSFORMED',
} as const;

export type CommonDbDataIssueType = typeof CommonDbDataIssueType[keyof typeof CommonDbDataIssueType];


export interface CommonDbEtlLogItem {
  'timestamp'?: string;
  'code': string;
  'message': string;
  'severity': CommonDbLogLevel;
  'source'?: string | null;
  'target'?: string | null;
}


export const CommonDbEtlStatus = {
  INITIALIZED: 'INITIALIZED',
  PENDING: 'PENDING',
  SKIPPED: 'SKIPPED',
  FAILED: 'FAILED',
  ERROR: 'ERROR',
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  MIXED: 'MIXED',
  PROCESSED: 'PROCESSED',
  SUCCESS: 'SUCCESS',
} as const;

export type CommonDbEtlStatus = typeof CommonDbEtlStatus[keyof typeof CommonDbEtlStatus];


export interface CommonDbFeatureFlagsResponseBody {
  'feature_flags': { [key: string]: boolean; };
}


export type CommonDbEpiFilter = CommonDbTypedCompositeFilter | CommonDbTypedDateRangeFilter | CommonDbTypedDatetimeRangeFilter | CommonDbTypedEqualsBooleanFilter | CommonDbTypedEqualsNumberFilter | CommonDbTypedEqualsStringFilter | CommonDbTypedEqualsUuidFilter | CommonDbTypedExistsFilter | CommonDbTypedNoFilter | CommonDbTypedNumberRangeFilter | CommonDbTypedNumberSetFilter | CommonDbTypedPartialDateRangeFilter | CommonDbTypedRegexFilter | CommonDbTypedStringSetFilter | CommonDbTypedUuidSetFilter;


export type CommonDbFiltersInner = CommonDbTypedCompositeFilter | CommonDbTypedDateRangeFilter | CommonDbTypedDatetimeRangeFilter | CommonDbTypedEqualsBooleanFilter | CommonDbTypedEqualsNumberFilter | CommonDbTypedEqualsStringFilter | CommonDbTypedEqualsUuidFilter | CommonDbTypedExistsFilter | CommonDbTypedNoFilter | CommonDbTypedNumberRangeFilter | CommonDbTypedNumberSetFilter | CommonDbTypedPartialDateRangeFilter | CommonDbTypedRegexFilter | CommonDbTypedStringSetFilter | CommonDbTypedUuidSetFilter;


export interface CommonDbHTTPValidationError {
  'detail'?: Array<CommonDbValidationError>;
}


export interface CommonDbHealthResponseBody {
  'status': CommonDbHealthStatus;
}


export const CommonDbHealthStatus = {
  HEALTHY: 'HEALTHY',
  UNHEALTHY: 'UNHEALTHY',
} as const;

export type CommonDbHealthStatus = typeof CommonDbHealthStatus[keyof typeof CommonDbHealthStatus];


export interface CommonDbIdentifierForUpload {
  'identifier_issuer_id'?: string | null;
  'identifier_issuer_code'?: string | null;
  'external_id': string;
}


export interface CommonDbIdentifierIssuer {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'code': string;
  'name': string;
  'description'?: string | null;
}


export interface CommonDbIdentityProvider {
  'name': string;
  'label': string;
  'issuer': string;
  'auth_protocol': CommonDbAuthProtocol;
  'oauth_flow'?: CommonDbOAuthFlow;
  'discovery_url'?: string | null;
  'client_id'?: string | null;
  'client_secret'?: string | null;
  'scope'?: string | null;
  'public'?: boolean;
}


export interface CommonDbLogItem {
  'level': CommonDbLogLevel;
  'command_id': string;
  'timestamp': string;
  'duration'?: number | null;
  'software_version': string;
  'topic': string;
  'detail'?: string | null;
}


export const CommonDbLogLevel = {
  FATAL: 'FATAL',
  ERROR: 'ERROR',
  WARN: 'WARN',
  INFO: 'INFO',
  DEBUG: 'DEBUG',
  TRACE: 'TRACE',
} as const;

export type CommonDbLogLevel = typeof CommonDbLogLevel[keyof typeof CommonDbLogLevel];


export interface CommonDbLogRequestBody {
  'log_items': Array<CommonDbLogItem>;
}


export const CommonDbLogicalOperator = {
  AND: 'AND',
  OR: 'OR',
  NOT: 'NOT',
  XOR: 'XOR',
  NAND: 'NAND',
  NOR: 'NOR',
  XNOR: 'XNOR',
  IMPLIES: 'IMPLIES',
  NIMPLIES: 'NIMPLIES',
} as const;

export type CommonDbLogicalOperator = typeof CommonDbLogicalOperator[keyof typeof CommonDbLogicalOperator];


export type CommonDbMembersInner = number | string;


export const CommonDbOAuthFlow = {
  AUTHORIZATION_CODE: 'AUTHORIZATION_CODE',
  CLIENT_CREDENTIALS: 'CLIENT_CREDENTIALS',
  RESOURCE_OWNER: 'RESOURCE_OWNER',
  HYBRID: 'HYBRID',
  DEVICE_AUTHORIZATION: 'DEVICE_AUTHORIZATION',
  PKCE: 'PKCE',
} as const;

export type CommonDbOAuthFlow = typeof CommonDbOAuthFlow[keyof typeof CommonDbOAuthFlow];


export interface CommonDbOrganization {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'code': string;
  'name': string;
  'description'?: string | null;
}


export interface CommonDbOrganizationAdminPolicy {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'organization_id': string;
  'organization'?: CommonDbOrganization;
  'user_id': string;
  'user'?: CommonDbUser;
  'is_active': boolean;
}


export interface CommonDbOrganizationContacts {
  'organization': CommonDbOrganization;
  'sites': Array<CommonDbSite>;
  'contacts': Array<CommonDbContact>;
}


export interface CommonDbOrganizationIdentifierIssuerLink {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'organization_id': string;
  'organization'?: CommonDbOrganization;
  'identifier_issuer_id': string;
  'identifier_issuer'?: CommonDbIdentifierIssuer;
}


export interface CommonDbOrganizationSet {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'name': string;
  'description'?: string | null;
}


export interface CommonDbOrganizationSetMember {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'organization_set_id': string;
  'organization_set'?: CommonDbOrganizationSet;
  'organization_id': string;
  'organization'?: CommonDbOrganization;
}


export interface CommonDbOutage {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'description'?: string | null;
  'active_from'?: string | null;
  'active_to'?: string | null;
  'visible_from'?: string | null;
  'visible_to'?: string | null;
  'is_active'?: boolean | null;
  'is_visible'?: boolean | null;
}


export interface CommonDbPackageMetadata {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'name': string;
  'version': string;
  'license'?: string | null;
  'homepage'?: string | null;
}


export const CommonDbPermissionType = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  EXECUTE: 'EXECUTE',
} as const;

export type CommonDbPermissionType = typeof CommonDbPermissionType[keyof typeof CommonDbPermissionType];


export interface CommonDbRetrieveOrganizationContactsRequestBody {
  'organization_id': string;
}


export interface CommonDbSite {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'organization_id': string;
  'organization'?: CommonDbOrganization;
  'name': string;
}


export interface CommonDbTypedCompositeFilter {
  'invert'?: boolean;
  'key'?: string | null;
  'filters': Array<CommonDbFiltersInner>;
  'operator'?: CommonDbLogicalOperator;
  'type': string;
}


export interface CommonDbTypedDateRangeFilter {
  'invert'?: boolean;
  'key'?: string;
  'lower_bound'?: string | null;
  'lower_bound_censor'?: CommonDbComparisonOperator;
  'upper_bound'?: string | null;
  'upper_bound_censor'?: CommonDbComparisonOperator;
  'type': string;
}


export interface CommonDbTypedDatetimeRangeFilter {
  'invert'?: boolean;
  'key'?: string;
  'lower_bound'?: string | null;
  'lower_bound_censor'?: CommonDbComparisonOperator;
  'upper_bound'?: string | null;
  'upper_bound_censor'?: CommonDbComparisonOperator;
  'type': string;
}


export interface CommonDbTypedEqualsBooleanFilter {
  'invert'?: boolean;
  'key'?: string;
  'value': boolean;
  'type': string;
}


export interface CommonDbTypedEqualsNumberFilter {
  'invert'?: boolean;
  'key'?: string;
  'value': CommonDbValue;
  'type': string;
}


export interface CommonDbTypedEqualsStringFilter {
  'invert'?: boolean;
  'key'?: string;
  'value': string;
  'type': string;
}


export interface CommonDbTypedEqualsUuidFilter {
  'invert'?: boolean;
  'key'?: string;
  'value': string;
  'type': string;
}


export interface CommonDbTypedExistsFilter {
  'invert'?: boolean;
  'key'?: string;
  'type': string;
}


export interface CommonDbTypedNoFilter {
  'invert'?: boolean;
  'key'?: boolean;
  'type': string;
}


export interface CommonDbTypedNumberRangeFilter {
  'invert'?: boolean;
  'key'?: string;
  'lower_bound'?: number | null;
  'lower_bound_censor'?: CommonDbComparisonOperator;
  'upper_bound'?: number | null;
  'upper_bound_censor'?: CommonDbComparisonOperator;
  'type': string;
}


export interface CommonDbTypedNumberSetFilter {
  'invert'?: boolean;
  'key'?: string;
  'members'?: Array<CommonDbMembersInner>;
  'type': string;
}


export interface CommonDbTypedPartialDateRangeFilter {
  'invert'?: boolean;
  'key'?: string;
  'lower_bound'?: string | null;
  'lower_bound_censor'?: CommonDbComparisonOperator;
  'upper_bound'?: string | null;
  'upper_bound_censor'?: CommonDbComparisonOperator;
  'type': string;
}


export interface CommonDbTypedRegexFilter {
  'invert'?: boolean;
  'key'?: string;
  'pattern': string;
  'type': string;
}


export interface CommonDbTypedStringSetFilter {
  'invert'?: boolean;
  'key'?: string;
  'members'?: Array<string>;
  'case_sensitive'?: boolean;
  'type': string;
}


export interface CommonDbTypedUuidSetFilter {
  'invert'?: boolean;
  'key'?: string;
  'members'?: Array<string>;
  'type': string;
}


export interface CommonDbUpdateDataCollectionSetDataCollectionRequestBody {
  'data_collection_set_members': Array<CommonDbDataCollectionSetMember>;
}


export interface CommonDbUpdateOrganizationIdentifierIssuerLinksRequestBody {
  'organization_identifier_issuer_links': Array<CommonDbOrganizationIdentifierIssuerLink>;
}


export interface CommonDbUpdateOrganizationSetOrganizationRequestBody {
  'organization_set_members': Array<CommonDbOrganizationSetMember>;
}


export interface CommonDbUpdateUserOwnOrganizationRequestBody {
  'organization_id': string;
}


export interface CommonDbUpdateUserRequestBody {
  'is_active': boolean | null;
  'roles': Array<string> | null;
  'organization_id': string | null;
}


export const CommonDbUploadAction = {
  ERROR: 'ERROR',
  UPDATE: 'UPDATE',
  CREATE: 'CREATE',
  SKIP: 'SKIP',
} as const;

export type CommonDbUploadAction = typeof CommonDbUploadAction[keyof typeof CommonDbUploadAction];


export interface CommonDbUploadResult {
  'logs'?: Array<CommonDbEtlLogItem>;
  'id'?: string | null;
  'status'?: CommonDbEtlStatus;
  'is_new'?: boolean;
}


export interface CommonDbUser {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'key'?: string | null;
  'email'?: string | null;
  'name'?: string | null;
  'description'?: string | null;
  'is_active'?: boolean;
  'roles': Array<string>;
  'organization_id': string;
  'organization'?: CommonDbOrganization;
}


export interface CommonDbUserInvitation {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'key'?: string | null;
  'email'?: string | null;
  'name'?: string | null;
  'description'?: string | null;
  'token': string;
  'expires_at': string;
  'roles': Array<string>;
  'invited_by_user_id': string;
  'invited_by_user'?: CommonDbUser;
  'organization_id': string;
  'organization'?: CommonDbOrganization;
}


export interface CommonDbUserInvitationConstraints {
  'created_at'?: string | null;
  'modified_at'?: string | null;
  'modified_by'?: string | null;
  'id'?: string | null;
  'roles': Array<string>;
  'organization_ids': Array<string>;
}


export interface CommonDbUserInvitationRequestBody {
  'key'?: string | null;
  'description'?: string | null;
  'roles': Array<string>;
  'organization_id': string;
}


export interface CommonDbUserNameEmail {
  'id'?: string | null;
  'name'?: string | null;
  'email': string | null;
}


export interface CommonDbValidationError {
  'msg': string;
  'type': string;
  'input'?: any;
  'ctx'?: object;
}


export type CommonDbValue = number | string;


export interface CommonDbAbacApi {
  organizationAdminPoliciesDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  organizationAdminPoliciesDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  organizationAdminPoliciesDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationAdminPoliciesGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationAdminPolicy>>>;
  organizationAdminPoliciesGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationAdminPolicy>>;
  organizationAdminPoliciesGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationAdminPolicy>>>;
  organizationAdminPoliciesPostOne(organizationAdminPolicy: CommonDbOrganizationAdminPolicy, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationAdminPolicy>>;
  organizationAdminPoliciesPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationAdminPolicy>>>;
  organizationAdminPoliciesPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationAdminPoliciesPostSome(organizationAdminPolicy: Array<CommonDbOrganizationAdminPolicy>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationAdminPolicy>>>;
  organizationAdminPoliciesPutOne(objectId: string, organizationAdminPolicy: CommonDbOrganizationAdminPolicy, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationAdminPolicy>>;
  organizationAdminPoliciesPutSome(organizationAdminPolicy: Array<CommonDbOrganizationAdminPolicy>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationAdminPolicy>>>;
  retrieveOrganizationAdminNameEmails(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUserNameEmail>>>;
}


export interface CommonDbAuthApi {
  identityProvidersGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbIdentityProvider>>>;
}


export interface CommonDbDefaultApi {
  redirectGet(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
}


export interface CommonDbOrganizationApi {
  contactsDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  contactsDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  contactsDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  contactsGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbContact>>>;
  contactsGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbContact>>;
  contactsGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbContact>>>;
  contactsPostOne(contact: CommonDbContact, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbContact>>;
  contactsPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbContact>>>;
  contactsPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  contactsPostSome(contact: Array<CommonDbContact>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbContact>>>;
  contactsPutOne(objectId: string, contact: CommonDbContact, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbContact>>;
  contactsPutSome(contact: Array<CommonDbContact>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbContact>>>;
  dataCollectionSetMembersDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  dataCollectionSetMembersDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  dataCollectionSetMembersDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  dataCollectionSetMembersGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSetMember>>>;
  dataCollectionSetMembersGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollectionSetMember>>;
  dataCollectionSetMembersGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSetMember>>>;
  dataCollectionSetMembersPostOne(dataCollectionSetMember: CommonDbDataCollectionSetMember, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollectionSetMember>>;
  dataCollectionSetMembersPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSetMember>>>;
  dataCollectionSetMembersPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  dataCollectionSetMembersPostSome(dataCollectionSetMember: Array<CommonDbDataCollectionSetMember>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSetMember>>>;
  dataCollectionSetMembersPutOne(objectId: string, dataCollectionSetMember: CommonDbDataCollectionSetMember, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollectionSetMember>>;
  dataCollectionSetMembersPutSome(dataCollectionSetMember: Array<CommonDbDataCollectionSetMember>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSetMember>>>;
  dataCollectionSetsDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  dataCollectionSetsDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  dataCollectionSetsDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  dataCollectionSetsGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSet>>>;
  dataCollectionSetsGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollectionSet>>;
  dataCollectionSetsGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSet>>>;
  dataCollectionSetsPostOne(dataCollectionSet: CommonDbDataCollectionSet, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollectionSet>>;
  dataCollectionSetsPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSet>>>;
  dataCollectionSetsPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  dataCollectionSetsPostSome(dataCollectionSet: Array<CommonDbDataCollectionSet>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSet>>>;
  dataCollectionSetsPutDataCollections(dataCollectionSetId: string, updateDataCollectionSetDataCollectionRequestBody: CommonDbUpdateDataCollectionSetDataCollectionRequestBody, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSetMember>>>;
  dataCollectionSetsPutOne(objectId: string, dataCollectionSet: CommonDbDataCollectionSet, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollectionSet>>;
  dataCollectionSetsPutSome(dataCollectionSet: Array<CommonDbDataCollectionSet>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollectionSet>>>;
  dataCollectionsDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  dataCollectionsDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  dataCollectionsDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  dataCollectionsGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollection>>>;
  dataCollectionsGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollection>>;
  dataCollectionsGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollection>>>;
  dataCollectionsPostOne(dataCollection: CommonDbDataCollection, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollection>>;
  dataCollectionsPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollection>>>;
  dataCollectionsPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  dataCollectionsPostSome(dataCollection: Array<CommonDbDataCollection>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollection>>>;
  dataCollectionsPutOne(objectId: string, dataCollection: CommonDbDataCollection, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbDataCollection>>;
  dataCollectionsPutSome(dataCollection: Array<CommonDbDataCollection>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbDataCollection>>>;
  identifierIssuersDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  identifierIssuersDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  identifierIssuersDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  identifierIssuersGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbIdentifierIssuer>>>;
  identifierIssuersGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbIdentifierIssuer>>;
  identifierIssuersGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbIdentifierIssuer>>>;
  identifierIssuersPostOne(identifierIssuer: CommonDbIdentifierIssuer, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbIdentifierIssuer>>;
  identifierIssuersPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbIdentifierIssuer>>>;
  identifierIssuersPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  identifierIssuersPostSome(identifierIssuer: Array<CommonDbIdentifierIssuer>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbIdentifierIssuer>>>;
  identifierIssuersPutOne(objectId: string, identifierIssuer: CommonDbIdentifierIssuer, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbIdentifierIssuer>>;
  identifierIssuersPutSome(identifierIssuer: Array<CommonDbIdentifierIssuer>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbIdentifierIssuer>>>;
  inviteUser(userInvitationRequestBody: CommonDbUserInvitationRequestBody, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUserInvitation>>;
  inviteUserConstraints(options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUserInvitationConstraints>>;
  organizationIdentifierIssuerLinksDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  organizationIdentifierIssuerLinksDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  organizationIdentifierIssuerLinksDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationIdentifierIssuerLinksGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationIdentifierIssuerLink>>>;
  organizationIdentifierIssuerLinksGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationIdentifierIssuerLink>>;
  organizationIdentifierIssuerLinksGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationIdentifierIssuerLink>>>;
  organizationIdentifierIssuerLinksPostOne(organizationIdentifierIssuerLink: CommonDbOrganizationIdentifierIssuerLink, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationIdentifierIssuerLink>>;
  organizationIdentifierIssuerLinksPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationIdentifierIssuerLink>>>;
  organizationIdentifierIssuerLinksPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationIdentifierIssuerLinksPostSome(organizationIdentifierIssuerLink: Array<CommonDbOrganizationIdentifierIssuerLink>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationIdentifierIssuerLink>>>;
  organizationIdentifierIssuerLinksPutOne(objectId: string, organizationIdentifierIssuerLink: CommonDbOrganizationIdentifierIssuerLink, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationIdentifierIssuerLink>>;
  organizationIdentifierIssuerLinksPutSome(organizationIdentifierIssuerLink: Array<CommonDbOrganizationIdentifierIssuerLink>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationIdentifierIssuerLink>>>;
  organizationSetMembersDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  organizationSetMembersDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  organizationSetMembersDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationSetMembersGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSetMember>>>;
  organizationSetMembersGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationSetMember>>;
  organizationSetMembersGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSetMember>>>;
  organizationSetMembersPostOne(organizationSetMember: CommonDbOrganizationSetMember, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationSetMember>>;
  organizationSetMembersPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSetMember>>>;
  organizationSetMembersPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationSetMembersPostSome(organizationSetMember: Array<CommonDbOrganizationSetMember>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSetMember>>>;
  organizationSetMembersPutOne(objectId: string, organizationSetMember: CommonDbOrganizationSetMember, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationSetMember>>;
  organizationSetMembersPutSome(organizationSetMember: Array<CommonDbOrganizationSetMember>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSetMember>>>;
  organizationSetsDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  organizationSetsDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  organizationSetsDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationSetsGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSet>>>;
  organizationSetsGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationSet>>;
  organizationSetsGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSet>>>;
  organizationSetsPostOne(organizationSet: CommonDbOrganizationSet, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationSet>>;
  organizationSetsPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSet>>>;
  organizationSetsPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationSetsPostSome(organizationSet: Array<CommonDbOrganizationSet>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSet>>>;
  organizationSetsPutOne(objectId: string, organizationSet: CommonDbOrganizationSet, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationSet>>;
  organizationSetsPutOrganizations(organizationSetId: string, updateOrganizationSetOrganizationRequestBody: CommonDbUpdateOrganizationSetOrganizationRequestBody, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSetMember>>>;
  organizationSetsPutSome(organizationSet: Array<CommonDbOrganizationSet>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationSet>>>;
  organizationsDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  organizationsDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  organizationsDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationsGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganization>>>;
  organizationsGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganization>>;
  organizationsGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganization>>>;
  organizationsPostOne(organization: CommonDbOrganization, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganization>>;
  organizationsPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganization>>>;
  organizationsPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  organizationsPostSome(organization: Array<CommonDbOrganization>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganization>>>;
  organizationsPutIdentifierIssuers(organizationId: string, updateOrganizationIdentifierIssuerLinksRequestBody: CommonDbUpdateOrganizationIdentifierIssuerLinksRequestBody, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganizationIdentifierIssuerLink>>>;
  organizationsPutOne(objectId: string, organization: CommonDbOrganization, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganization>>;
  organizationsPutSome(organization: Array<CommonDbOrganization>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOrganization>>>;
  retrieveOrganizationContacts(retrieveOrganizationContactsRequestBody: CommonDbRetrieveOrganizationContactsRequestBody, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOrganizationContacts>>;
  sitesDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  sitesDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  sitesDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  sitesGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbSite>>>;
  sitesGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbSite>>;
  sitesGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbSite>>>;
  sitesPostOne(site: CommonDbSite, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbSite>>;
  sitesPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbSite>>>;
  sitesPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  sitesPostSome(site: Array<CommonDbSite>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbSite>>>;
  sitesPutOne(objectId: string, site: CommonDbSite, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbSite>>;
  sitesPutSome(site: Array<CommonDbSite>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbSite>>>;
  updateUser(objectId: string, updateUserRequestBody: CommonDbUpdateUserRequestBody, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUser>>;
  updateUserOwnOrganization(updateUserOwnOrganizationRequestBody: CommonDbUpdateUserOwnOrganizationRequestBody, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUser>>;
  userInvitationsDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  userInvitationsDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  userInvitationsDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  userInvitationsGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUserInvitation>>>;
  userInvitationsGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUserInvitation>>;
  userInvitationsGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUserInvitation>>>;
  userInvitationsPostOne(userInvitation: CommonDbUserInvitation, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUserInvitation>>;
  userInvitationsPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUserInvitation>>>;
  userInvitationsPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  userInvitationsPostSome(userInvitation: Array<CommonDbUserInvitation>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUserInvitation>>>;
  userInvitationsPutOne(objectId: string, userInvitation: CommonDbUserInvitation, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUserInvitation>>;
  userInvitationsPutSome(userInvitation: Array<CommonDbUserInvitation>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUserInvitation>>>;
  userMeGetOne(options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUser>>;
  userMeRetrievePermissions(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbApiPermission>>>;
  userRegistrationsPostOne(token: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUser>>;
  usersDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  usersDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  usersDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  usersGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUser>>>;
  usersGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUser>>;
  usersGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUser>>>;
  usersPostOne(user: CommonDbUser, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUser>>;
  usersPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUser>>>;
  usersPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  usersPostSome(user: Array<CommonDbUser>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUser>>>;
  usersPutOne(objectId: string, user: CommonDbUser, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbUser>>;
  usersPutSome(user: Array<CommonDbUser>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbUser>>>;
}


export interface CommonDbSystemApi {
  health(options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbHealthResponseBody>>;
  log(logRequestBody: CommonDbLogRequestBody, options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  outagesDeleteAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<any>>;
  outagesDeleteOne(objectId: any, options?: RawAxiosRequestConfig): Promise<AxiosResponse<string>>;
  outagesDeleteSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  outagesGetAll(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOutage>>>;
  outagesGetOne(objectId: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOutage>>;
  outagesGetSome(ids: string, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOutage>>>;
  outagesPostOne(outage: CommonDbOutage, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOutage>>;
  outagesPostQuery(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOutage>>>;
  outagesPostQueryIds(filter: CommonDbEpiFilter, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<string>>>;
  outagesPostSome(outage: Array<CommonDbOutage>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOutage>>>;
  outagesPutOne(objectId: string, outage: CommonDbOutage, options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbOutage>>;
  outagesPutSome(outage: Array<CommonDbOutage>, options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOutage>>>;
  retrieveFeatureFlags(options?: RawAxiosRequestConfig): Promise<AxiosResponse<CommonDbFeatureFlagsResponseBody>>;
  retrieveLicenses(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbPackageMetadata>>>;
  retrieveOutages(options?: RawAxiosRequestConfig): Promise<AxiosResponse<Array<CommonDbOutage>>>;
}
