name: ci

on:
  pull_request:

jobs:
  validate:
    name: Validate code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
        with:
          node-version: 22
      - run: npm ci
      - run: npm run validate
